runtime: python39

handlers:
- url: /static
  static_dir: static

- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|css|js)$
  
- url: /.*
  static_files: static/index.html
  upload: static/index.html
